# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://vaishnaray1.github.io'
baseurl:             'appdev2/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Vaishnavi Narayanan
  url:               https://www.linkedin.com/in/vaish-narayanan/
  email:             vaishnavi.narayanan@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
